package org.schema;

/**
 * 
 * A service provided by an organization, e.g. delivery service, print services,
 * etc.
 * 
 * @fullPath Thing > Intangible > Service
 * 
 * @author Texelz (by Onhate)
 * 
 */
public class Service extends Intangible {

	private ServiceChannel availableChannel;
	private Thing produces;
	private Object provider;
	private AdministrativeArea serviceArea;
	private Audience serviceAudience;
	private String serviceType;

	/**
	 * A means of accessing the service (e.g. a phone bank, a web site, a
	 * location, etc.)
	 */
	public ServiceChannel getAvailableChannel() {
		return this.availableChannel;
	}

	/**
	 * A means of accessing the service (e.g. a phone bank, a web site, a
	 * location, etc.)
	 */
	public void setAvailableChannel(ServiceChannel availableChannel) {
		this.availableChannel = availableChannel;
	}

	/**
	 * The tangible thing generated by the service, e.g. a passport, permit,
	 * etc.
	 */
	public Thing getProduces() {
		return this.produces;
	}

	/**
	 * The tangible thing generated by the service, e.g. a passport, permit,
	 * etc.
	 */
	public void setProduces(Thing produces) {
		this.produces = produces;
	}

	/**
	 * The organization or agency that is providing the service.
	 * 
	 * @see Organization
	 * @see Person
	 */
	public Object getProvider() {
		return this.provider;
	}

	/**
	 * The organization or agency that is providing the service.
	 * 
	 * @see Organization
	 * @see Person
	 */
	public void setProvider(Object provider) {
		this.provider = provider;
	}

	/**
	 * The geographic area where the service is provided.
	 */
	public AdministrativeArea getServiceArea() {
		return this.serviceArea;
	}

	/**
	 * The geographic area where the service is provided.
	 */
	public void setServiceArea(AdministrativeArea serviceArea) {
		this.serviceArea = serviceArea;
	}

	/**
	 * The audience eligible for this service.
	 */
	public Audience getServiceAudience() {
		return this.serviceAudience;
	}

	/**
	 * The audience eligible for this service.
	 */
	public void setServiceAudience(Audience serviceAudience) {
		this.serviceAudience = serviceAudience;
	}

	/**
	 * The type of service being offered, e.g. veterans' benefits, emergency
	 * relief, etc.
	 */
	public String getServiceType() {
		return this.serviceType;
	}

	/**
	 * The type of service being offered, e.g. veterans' benefits, emergency
	 * relief, etc.
	 */
	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}
}
